mysite/mutapp/urls.py
from django.urls import path

from . import views

app_name = 'mutapp'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('metadata/<int:pk>/', views.DetailViewMeta.as_view(), name='metadata'),
    path('mutation/<int:pk>/', views.DetailViewMut.as_view(), name='mutation'),
    path('queryname/', views.query_by_name, name='queryname'),
    path('querymutation/', views.query_by_mutation, name='querymutation'),
    path('multimut/', views.query_by_multi_mutation, name='multimut'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('mutapp/', include('mutapp.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/mutapp/models.py
from django.db import models

class Covid19metadata(models.Model):
    virus_strain_name = models.CharField(max_length=255)
    accession_id = models.CharField(max_length=255, blank=True)
    data_source = models.CharField(max_length=255, blank=True)
    related_id = models.CharField(max_length=255, blank=True)
    nuc_completeness = models.CharField(max_length=255, blank=True)
    sequence_length = models.IntegerField(default=0, blank=True)
    sequence_quality = models.CharField(max_length=255, blank=True)
    quality_assessment = models.TextField(blank=True)
    host = models.CharField(max_length=255, blank=True)
    sample_collection_date = models.DateTimeField(blank=True)
    location = models.TextField(blank=True)
    originating_lab = models.TextField(blank=True)
    submission_date = models.DateTimeField(blank=True)
    submission_lab = models.TextField(blank=True)
    create_time = models.DateTimeField(blank=True)
    last_update_time = models.DateTimeField(blank=True)

    def __str__(self):
        return '#--' + str(self.id) + '---|---' + self.virus_strain_name + '---|---' + self.location

class SampleMutlist(models.Model):
    virus_strain_name = models.CharField(max_length=255)
    mutation = models.TextField(blank=True)
    metadata = models.ForeignKey(Covid19metadata, on_delete=models.CASCADE)

    def __str__(self):
        return '#--' + str(self.id) + '---|---' + self.virus_strain_name

class MutSamplelist(models.Model):
    ti_tv = models.CharField(max_length=255, blank=True)
    start = models.IntegerField(blank=True)
    end = models.IntegerField(blank=True)
    ref_var = models.TextField(blank=True)
    gene = models.CharField(max_length=255, blank=True)
    ns_s = models.CharField(max_length=255, blank=True)
    count = models.IntegerField(blank=True)
    sample = models.TextField(blank=True)
    meta_id = models.TextField(blank=True)

    def __str__(self):
        return '#--' + str(self.id) + '--|--' + str(self.start) + ':' + self.ref_var + '--|--' + str(self.count)

mysite/mutapp/views.py
from django.http import HttpResponseRedirect,HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Covid19metadata, SampleMutlist, MutSamplelist

class IndexView(generic.ListView):
    template_name = 'mutapp/index.html'
    context_object_name = 'latest_sequence_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Covid19metadata.objects.order_by('-sample_collection_date')[:30]

class DetailViewMeta(generic.DetailView):
    model = Covid19metadata
    #template_name = 'mutapp/covid19metadata_detail.html'


# query single mutation, version 1.0
# class DetailViewMut(generic.DetailView):
#     model = MutSamplelist
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         meta_name_str = self.object.sample
#         meta_name_list = meta_name_str.split(';')
#         meta_list = []
#
#         for meta_name in meta_name_list:
#             try:
#                 meta_id = Covid19metadata.objects.get(virus_strain_name=meta_name).id
#             except (LookupError,Covid19metadata.DoesNotExist):
#                 meta_id = 1
#             meta_list.append({'meta_name':meta_name, 'meta_id':meta_id})
#
#         context['meta_list'] = meta_list
#         return context
#     #template_name = 'mutapp/mutsamplelist_detail.html'

# query single mutation, version 2.0
class DetailViewMut(generic.DetailView):
    model = MutSamplelist

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        meta_name_str = self.object.sample
        meta_name_list = meta_name_str.split(';')
        meta_list = []

        meta_id_srt = self.object.meta_id
        meta_id_list = meta_id_srt.split(';')
        meta_name_id_tlist = zip(meta_name_list,meta_id_list)

        for i in meta_name_id_tlist:
            meta_list.append({'meta_name':i[0], 'meta_id':i[1]})

        context['meta_list'] = meta_list
        return context
    #template_name = 'mutapp/mutsamplelist_detail.html'

def query_by_name(request):
    smaple = get_object_or_404(Covid19metadata, virus_strain_name=request.POST['queryname'])
    return HttpResponseRedirect(reverse('mutapp:metadata', args=(smaple.id,)))

def query_by_mutation(request):
    mutation_sample = get_object_or_404(MutSamplelist,
                                        start=request.POST['querypos'], ref_var=request.POST['querymut'])
    return HttpResponseRedirect(reverse('mutapp:mutation', args=(mutation_sample.id,)))


# query multiple mutations, version 1.0
# def query_by_multi_mutation(request):
#     #- get query_set
#     textarea = request.POST['multimut']
#     start_mut = []
#     list_temp = textarea.split()
#     for i in list_temp:
#         start_mut.append(tuple(i.split(';')))
#     my_queryset = []
#     for i in start_mut:
#         try:
#             mut_sample = MutSamplelist.objects.get(start=i[0], ref_var=i[1])
#         except (LookupError, MutSamplelist.DoesNotExist):
#             print('LookupError: '+i[0]+';'+i[1])
#         else:
#             my_queryset.append(mut_sample)
#     vname_list = []
#     for i in my_queryset:
#         vname_set = set(i.sample.upper().split(';'))#-----------------------------------
#         vname_list.append(tuple(vname_set))
#
#     #- build new table
#     smut_qset_vname = [start_mut, my_queryset, vname_list]
#     smut_qset_vname_transpose = list(map(list, zip(*smut_qset_vname)))
#
#     #- count the number of hits
#     vname_all_tuple = ()
#     for i in vname_list:
#         vname_all_tuple = vname_all_tuple + i
#     vname_count_dic = {}
#     for k in vname_all_tuple:
#         vname_count_dic[k] = vname_count_dic.get(k, 0) + 1
#     vname_count_mut_list = []
#     for k,v in vname_count_dic.items():
#         mut_tep = ()
#         for i in smut_qset_vname_transpose:
#             if k in i[2]:
#                 mut_tep = mut_tep + i[0]
#         vname_count_mut_list.append([k,v,mut_tep])
#     vname_count_mut_list.sort(key=lambda x:x[1], reverse=True)
#
#     #- truncated
#     truncated = 30
#     if len(vname_count_mut_list)>truncated:
#         vname_count_mut_list_trunc = vname_count_mut_list[0:truncated]
#     else:
#         vname_count_mut_list_trunc = vname_count_mut_list
#
#     #- get object
#     vname_count_mut_list_trunc_obj = vname_count_mut_list_trunc
#     i = 0
#     while i<len(vname_count_mut_list_trunc_obj):
#         try:
#             metaobj = Covid19metadata.objects.get(virus_strain_name=vname_count_mut_list_trunc[i][0])
#         except (LookupError, Covid19metadata.DoesNotExist):
#             print('LookupError:',vname_count_mut_list_trunc[i])
#             vname_count_mut_list_trunc_obj[i].append(Covid19metadata.objects.get(pk=1))
#         else:
#             vname_count_mut_list_trunc_obj[i].append(metaobj)
#         i = i + 1
#
#     #return HttpResponse(vname_count_mut_list_trunc_obj)
#     context = {'hits_list': vname_count_mut_list_trunc_obj}
#     return render(request, 'mutapp/multimut_hits.html', context)

# query multiple mutations, version 2.0
def query_by_multi_mutation(request):
    #- get query_set
    textarea = request.POST['multimut']
    start_mut = []
    list_temp = textarea.split()
    for i in list_temp:
        start_mut.append(tuple(i.split(';')))
    my_queryset = []
    for i in start_mut:
        try:
            mut_sample = MutSamplelist.objects.get(start=i[0], ref_var=i[1])
        except (LookupError, MutSamplelist.DoesNotExist):
            print('LookupError: '+i[0]+';'+i[1])
        else:
            my_queryset.append(mut_sample)

    vname_tlist =[]
    metaid_tlist = []
    for i in my_queryset:
        vname_tuple = tuple(i.sample.split(';'))
        metaid_tuple = tuple(i.meta_id.split(';'))
        vname_tlist.append(vname_tuple)
        metaid_tlist.append(metaid_tuple)

    #- build new table
    smut_qset_metaid = [start_mut, my_queryset, metaid_tlist]
    smut_qset_metaid_transpose = list(map(list, zip(*smut_qset_metaid)))

    #- count the number of hits
    metaid_all_tuple = ()
    for i in metaid_tlist:
        metaid_all_tuple = metaid_all_tuple + i
    metaid_count_dic = {}
    for k in metaid_all_tuple:
        metaid_count_dic[k] = metaid_count_dic.get(k, 0) + 1
    metaid_count_mut_list = []
    for k,v in metaid_count_dic.items():
        mut_tep = ()
        for i in smut_qset_metaid_transpose:
            if k in i[2]:
                mut_tep = mut_tep + i[0]
        metaid_count_mut_list.append([k,v,mut_tep])
    metaid_count_mut_list.sort(key=lambda x:x[1], reverse=True)

    # #- truncated
    # truncated = 5000
    # if len(metaid_count_mut_list)>truncated:
    #     metaid_count_mut_list_trunc = metaid_count_mut_list[0:truncated]
    # else:
    #     metaid_count_mut_list_trunc = metaid_count_mut_list

    #- truncated v2
    if metaid_count_mut_list[0][0] == '1':
        del metaid_count_mut_list[0]
    metaid_count_mut_list_trunc = []
    for i in metaid_count_mut_list:
        if i[1] == metaid_count_mut_list[0][1]:
            metaid_count_mut_list_trunc.append(i)
        else:
            break

    #- get object
    metaid_count_mut_list_trunc_obj = metaid_count_mut_list_trunc
    i = 0
    location_list = []
    while i<len(metaid_count_mut_list_trunc_obj):
        try:
            metaobj = Covid19metadata.objects.get(pk=metaid_count_mut_list_trunc[i][0])
            location_list.append(metaobj.location)
        except (LookupError, Covid19metadata.DoesNotExist):
            print('LookupError:',metaid_count_mut_list_trunc[i])
            metaid_count_mut_list_trunc_obj[i].append(Covid19metadata.objects.get(pk=1))
        else:
            metaid_count_mut_list_trunc_obj[i].append(metaobj)
        i = i + 1

    # - sort by date
    metaid_count_mut_list_trunc_obj.sort(key=lambda x:x[3].sample_collection_date,reverse=True)

    #- geographic distibution
    country_list = [i.split('/')[0].strip() for i in location_list]
    country_count_dic = {}
    for k in country_list:
        country_count_dic[k] = country_count_dic.get(k, 0) + 1
    country_count_tlist = []
    for k, v in country_count_dic.items():
        country_count_tlist.append((k,v))
    country_count_tlist.sort(key=lambda x: x[1], reverse=True)

    #return HttpResponse(country_count_tlist)
    context = {'hits_list': metaid_count_mut_list_trunc_obj, 'country_count':country_count_tlist}
    return render(request, 'mutapp/multimut_hits.html', context)

mysite/mutapp/templates/mutapp/covid19metadata_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3>{{ covid19metadata.virus_strain_name }}</h3>

<ul>
    {% for samplemut in covid19metadata.samplemutlist_set.all %}
        <li>Mutaion:{{ samplemut.mutation }} </li>
    {% endfor %}
    <li>Location:{{ covid19metadata.location }} </li>
    <li>Host:{{ covid19metadata.host }} </li>
    <li>Sequence length:{{ covid19metadata.sequence_length }} </li>
    <li>Collection date:{{ covid19metadata.sample_collection_date }} </li>
    <li>Date source:{{ covid19metadata.data_source }} </li>
</ul>

<a href="{% url 'mutapp:index' %}"> >>Back<< </a>

</body>
</html>

mysite/mutapp/templates/mutapp/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>My test page</title>
</head>
<body>
<h3>Mutation inquiry</h3>

<form action="{% url 'mutapp:queryname' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>Query by name:</legend><br>
        <label>Virus Strain Name:
            <input type="text" name="queryname" size="35" >
        </label>
        <p>Input example:</p>
        <p>2019-NCOV/USA-AZ1/2020</p>
        <input type="submit" value="Query">
    </fieldset>
</form>
<br><br>

<form action="{% url 'mutapp:querymutation' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>Query by single-mutation:</legend><br>
        <label>Start:
            <input type="text" name="querypos">
        </label>
        <label>Mutation:
            <input type="text" name="querymut" size="30">
        </label>
        <p>Input example:</p>
        <p>Start: 25534</p>
        <p>Mutation: G/T</p>
        <input type="submit" value="Query">
    </fieldset>
</form>
<br><br>

<form action="{% url 'mutapp:multimut' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>Query by multi-mutation:</legend><br>
        <label>Start and Mutation:<br><br>
            <textarea name="multimut" cols="40" rows="10"></textarea>
        </label>
        <p>Input example:</p>
        <p>241;C/T<br>3037;C/T<br>6026;C/T<br>14408;C/T<br>23403;A/G<br>28881;G/A<br>.....</p>
        <input type="submit" value="Query">
    </fieldset>
</form>

<br><br>
<hr>
<h3>Latest submitted sequence:</h3>
{% if latest_sequence_list %}
    <ul>
        {% for sequence in latest_sequence_list %}
            <li><a href="{% url 'mutapp:metadata' sequence.id %}">{{ forloop.counter }}---{{ sequence.virus_strain_name }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
<hr><hr>
<p>Version: 2.0</p><p>Data release: 2020-9-11</p>
<br>
</body>
</html>

mysite/mutapp/templates/mutapp/multimut_hits.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3>Mutation hit sequence:</h3>
<table width="1400" frame="box">
    <td>Virus strain name</td>
    <td>Number of hits</td>
    <td align="center">Hits(Start/Ref_var)</td>
    <td>Location</td>
    <td>Colletion time</td>
    {% if hits_list %}
        {% for hit_one in hits_list %}
            <tr>
                <td><a href="{% url 'mutapp:metadata' hit_one.3.id %}">{{ forloop.counter }}---{{ hit_one.3.virus_strain_name }}</a></td>
                <td align="center">{{ hit_one.1 }}</td>
                <td>{{ hit_one.2 }}</td>
                <td>{{ hit_one.3.location }}</td>
                <td>{{ hit_one.3.sample_collection_date }}</td>
            </tr>
        {% endfor %}
        </table>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
<br><br><hr><br>
<h3>Geographical distribution:</h3>
<ol>
    {% for one_country in country_count %}
        <li>{{ one_country.0 }}:{{ one_country.1 }}</li>
    {% endfor %}
</ol>
<br>
<a href="{% url 'mutapp:index' %}"> >>Back<< </a>
<br><br><hr><br>
</body>
</html>

mysite/mutapp/templates/mutapp/mutsamplelist_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3>Hit samples:</h3>
<br>
<table width="600" frame="box">
    <tr>
    <th>Ti_Tv</th>
    <th>Start</th>
    <th>Ref_var</th>
    <th>Gene</th>
    <th>NS_S</th>
    <th>Count</th>
    </tr>
    <tr>
        <td align="center">{{ mutsamplelist.ti_tv }}</td>
        <td align="center">{{ mutsamplelist.start }}</td>
        <td align="center">{{ mutsamplelist.ref_var }}</td>
        <td align="center">{{ mutsamplelist.gene }}</td>
        <td align="center">{{ mutsamplelist.ns_s }}</td>
        <td align="center">{{ mutsamplelist.count }}</td>
    </tr>
</table>
<br><br><hr>
{% if meta_list%}
    <ol>
        {% for mete_data in meta_list %}
            <li><a href="{% url 'mutapp:metadata' mete_data.meta_id %}">{{ mete_data.meta_name }}</a></li>
        {% endfor %}
    </ol>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<hr><br><br>
<a href="{% url 'mutapp:index' %}"> >>Back<< </a>
</body>
</html>